name: Create and Deploy App
description: create and deploy plugin code
on:
  workflow_dispatch:
    inputs:
      folderName:
        description: "Folder name to create"
        required: true
      files:
        description: "Base64 or JSON encoded files object"
        required: true

jobs:
  create-and-deploy:
    name: Create and deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Create folder and decode files
        run: |
          mkdir -p "${{ github.event.inputs.folderName }}"
          echo "create directory ${{ github.event.inputs.folderName }}"
          echo "${{ github.event.inputs.files }}" > temp.json
          node -e '
          const fs = require("fs");
          const fileContents = fs.readFileSync("temp.json", "utf8");
          console.log(JSON.parse(fileContents));
          '
          
        env:
          FOLDER: ${{ github.event.inputs.folderName }}

      - name: output
        run: echo "hello world"
